export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  CREW_NOT_FOUND: "CREW_NOT_FOUND",
  HANDOVER_BLOCKED: "HANDOVER_BLOCKED",
  HANDOVER_TARGET_INVALID: "HANDOVER_TARGET_INVALID"
} as const;
