export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  HANDOVER_BLOCKED: "HANDOVER_BLOCKED",
  HANDOVER_TARGET_INVALID: "HANDOVER_TARGET_INVALID",
  HANDOVER_TICKET_NOT_FOUND: "HANDOVER_TICKET_NOT_FOUND",
  HANDOVER_CREW_NOT_FOUND: "HANDOVER_CREW_NOT_FOUND",
  HANDOVER_CONFLICT: "HANDOVER_CONFLICT"
} as const;
